# Database
spring.datasource.url=jdbc:mysql://localhost:3306/bug_tracker
spring.datasource.username=root
spring.datasource.password=Vikas2808007@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Server
server.port=8080

# JWT
app.jwt.secret=bugtrackerSecretKey2024SuperLongKeyForHMACSHA256Algorithm
app.jwt.expiration=86400000

# Jackson - clean date format
#spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

# Silence security warning
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR